name: Next.js Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # placeholders so build won’t crash in CI
      DATABASE_URL: "postgres://user:pass@localhost:5432/db"
      GOOGLE_GENERATIVE_AI_API_KEY: "test-key"
      NEXT_PUBLIC_APP_URL: "http://localhost"
      NEXT_TELEMETRY_DISABLED: "1"
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run tests
        run: npm test --if-present

      - name: Build Next.js app
        run: npm run build
